nydusd: register signal after eventfd is created.
Otherwise, signal handler wants to read eventfd which is actually a
None.

---

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None`
value', src/bin/nydusd.rs:693:9
note: run with `RUST_BACKTRACE=1` environment variable to display a
backtrace
fatal runtime error: failed to initiate panic, error 5
fish: Job 1, “sudo /home/imeoer/nydus-rs/targ…” terminated by signal
SIGABRT (Abort)

Signed-off-by: Changwei Ge <chge@linux.alibaba.com>