Build: fix compile error for `make docker-static`
Upgrade sendfd crate version `v0.3.3` to fix compatibility with musl:

```
$ make docker-static

error[E0063]: missing field `__pad1` in initializer of `libc::cmsghdr`
  --> sendfd-0.3.1/src/lib.rs:92:13
   |
92 |             libc::cmsghdr {
   |             ^^^^^^^^^^^^^ missing `__pad1`
```

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>