builder: use OsStr to represent file path
Not all files' names are Unicode/utf-8 encoded.
So we might fail in converting OsString to String.
In fact we don't have to convert it as OsStr implements `PartialEq` too.
For string operation like `starts_with`, we just try and if it can't be
converted it can't be whiteout either.

---

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
"\xD3\xC0н\xB7\xE9ӽ\xE2\xE6в\xB3\xB7\xD0Գ\xBD\xB3\xA2\xB8\xAC\xB7\xE4Ӷ\xD3\xC1\xE2\xE7\xD0\xCF\xE2\u{7f2}\xFC\xB7\xED\xE2\xE3\xB7帥\xB8\xA3\xE2\xFBл\xE2\xF0Ӿӣ\xB2\xFC\xE2\xF3\xD0\xC6Ӣ\xB7\xFE\xB7\xF4\xB7\xEB\xD0ϳ\xB1\xE2\xE7\xE2\xF5\xD0\xC0\xE2\xEF\xB7\xED\xB3\xB1\xB8\xA3\xB2\xF9\xB2\xF4\xD0ǳ\xB5\xB7\xE9\xE2\xF7\xB3\xB2\xE3\xA1\xD0\xD0\xD0ĳ\xAD\xD3\xC0ӷ\xB3\xC1\xD0\u{337}\xFD\xB7\xFDөз\xD0\xCB.regular"',
builder/src/node.rs:361:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at
/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at
/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as
core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: core::result::Result<T,E>::unwrap
             at
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: nydus_builder::node::Node::name
             at builder/src/node.rs:361
  16: nydus_builder::node::Node::build_inode
             at builder/src/node.rs:282
  17: nydus_builder::node::Node::new
             at builder/src/node.rs:115
  18: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:148
  19: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  20: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  21: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  22: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  23: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  24: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  25: nydus_builder::tree::FilesystemTreeBuilder::load_children
             at builder/src/tree.rs:173
  26: nydus_builder::tree::Tree::from_filesystem
             at builder/src/tree.rs:220
  27: nydus_builder::builder::Builder::build_from_filesystem
             at builder/src/builder.rs:297
  28: nydus_builder::builder::Builder::build
             at builder/src/builder.rs:490
  29: nydus_image::main
             at src/bin/nydus-image.rs:279
  30: std::rt::lang_start::{{closure}}
             at
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  31: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  32: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  33: std::panicking::try
             at src/libstd/panicking.rs:274
  34: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  35: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  36: std::rt::lang_start
             at
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67

Signed-off-by: Changwei Ge <chuanlang.gcw@antfin.com>