Builder: fix panic on upper prefetch table build
Should clear all cached states including prefetch readahead files
for upper layer build, otherwise the following error will occur:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/nydus-image/core/blob.rs:169:72
```

This bug was introduced from commit 4db5d7, the ctx.nodes index
will overflow because the list of readahead files generated by
the last build_rafs call.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>