nydus-image: skip xattr if underlying fs does not support it
Currently nydus-image assumes the underlying fs supports xattr,
otherwise it will error out with EOPNOTSUPP. e.g.

Error: Os { code: 95, kind: Other, message: "Not supported" }

This makes nydus-image unusuable in some env, e.g. converting a dir on
virtiofs which doesn't have xattr support.

Fix it by just ignoring EOPNOTSUPP when building inode xattr, so the
image is built without xattr.

Signed-off-byr Eryu Guan <eguan@linux.alibaba.com>