fix compiling error caused by  conflict merge
cargo clippy --features=virtiofs --target-dir target-virtiofs -- -Dclippy::all
    Checking upgrade-manager v0.1.0 (/lfs2/git_repo/nydus-rs/upgrade)
    Checking rafs v0.1.0 (/lfs2/git_repo/nydus-rs/rafs)
    Checking nydus-api v0.1.0 (/lfs2/git_repo/nydus-rs/api)
    Checking nydus-rs v0.1.0 (/lfs2/git_repo/nydus-rs)
error: redundant closure found
   --> src/bin/nydusd/daemon.rs:283:43
    |
283 |             .map(|files| files.iter().map(|f| PathBuf::from(f)).collect());
    |                                           ^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `PathBuf::from`
    |
    = note: `-D clippy::redundant-closure` implied by `-D clippy::all`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

error: aborting due to previous error

error: could not compile `nydus-rs`.

Signed-off-by: Changwei Ge <chge@linux.alibaba.com>